[package]
name = "astria_render"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.17"
raw-window-handle = "0.5"
winit = "0.28"
anyhow = "1.0"
bytemuck = { version = "1.14", features = ["derive"] }
