[package]
name = "aurion_core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.6", features = ["v4", "serde"] }
petgraph = "0.6"
parking_lot = "0.12"
anyhow = "1.0"
